# sysu219 关节目标快照
# timestamp: 2026-09-23T10:57:45.830475
joint_targets_rad:
  - {name: FR_hip_joint, position: -0.229000}
  - {name: FR_thigh_joint, position: 1.191000}
  - {name: FR_calf_joint, position: -2.665000}
  - {name: FL_hip_joint, position: 0.229000}
  - {name: FL_thigh_joint, position: 1.191000}
  - {name: FL_calf_joint, position: -2.665000}
  - {name: RR_hip_joint, position: -0.279000}
  - {name: RR_thigh_joint, position: 1.362000}
  - {name: RR_calf_joint, position: -2.588000}
  - {name: RL_hip_joint, position: 0.279000}
  - {name: RL_thigh_joint, position: 1.362000}
  - {name: RL_calf_joint, position: -2.588000}
