# sysu219 关节目标快照
# timestamp: 2026-09-23T10:51:10.769978
joint_targets_rad:
  - {name: FR_hip_joint, position: -0.428000}
  - {name: FR_thigh_joint, position: 1.230000}
  - {name: FR_calf_joint, position: -2.530000}
  - {name: FL_hip_joint, position: 0.428000}
  - {name: FL_thigh_joint, position: 1.230000}
  - {name: FL_calf_joint, position: -2.530000}
  - {name: RR_hip_joint, position: -0.274000}
  - {name: RR_thigh_joint, position: 1.098000}
  - {name: RR_calf_joint, position: -2.530000}
  - {name: RL_hip_joint, position: 0.274000}
  - {name: RL_thigh_joint, position: 1.098000}
  - {name: RL_calf_joint, position: -2.530000}
